"""empty message

Revision ID: 51454ec190bc
Revises: f7d1be81ebfb
Create Date: 2016-11-25 17:11:45.370000

"""

# revision identifiers, used by Alembic.
revision = '51454ec190bc'
down_revision = 'f7d1be81ebfb'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('avatar_hash', sa.String(length=32), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'avatar_hash')
    ### end Alembic commands ###
