"""empty message

Revision ID: 921f0daf30c2
Revises: None
Create Date: 2016-11-09 17:58:15.255000

"""

# revision identifiers, used by Alembic.
revision = '921f0daf30c2'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password_hash', sa.String(length=128), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'password_hash')
    ### end Alembic commands ###
