"""empty message

Revision ID: b2a226d215cb
Revises: 921f0daf30c2
Create Date: 2016-11-10 22:49:13.949000

"""

# revision identifiers, used by Alembic.
revision = 'b2a226d215cb'
down_revision = '921f0daf30c2'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('email', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_column('users', 'email')
    ### end Alembic commands ###
